### ISSUE TITLE
Submitting the same transaction with the same seq num should fail with "seq num" error

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/horizon#20]
Right now, if I submit the same transaction with the same sequence number, it says "already_finished".
Failing with "incorrect seq num" would be more correct.

**Comment by nullstyle** [comment]
I believe you're misunderstanding what "already finished" means.  It means that we looked at the transaction you submitted, and noticed that we have _the exact same transaction_ already committed to the ledger.  

You'll get a different error code if the transaction differs in any way from the transaction submitted at that sequence number.

This allows transaction submission to be idempotent, which in general is preferable, but is important in scenarios where it is tough to get a response from the server (for whatever reason):  simply continue submitting the transaction to the server until you get a response.  You need not query the ledger state after each submission, as you would if it were not idempotent.
