### ISSUE TITLE
Horizon crash after sending payment transaction

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/horizon#29]
the response I get back was success and the transaction successfully creates the account.

envelope:
899b2840ed5636c56ddc5f14b23975f79f1ba2388d2694e4c56ecdddc960e5ef000003e8000000000000000100000000ffffffff00000000000000010000000000000000675a0873e89b2ba0e998cf8964dbc24b70813e2b38254ba6548164b979b7af7f000000000000000001312d00000000200000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000001312d0000000001899b2840b802f061836477a648b16d4ba73262c12e1267a81ef6485789c625c1ef435c0d068c81452f4b8f6cd68c49d8415d58c6c0b5432f081649bff540288fa7f3cb0a

exception:
Actor crashed!
XDR::ReadError: VarArray length 16777216 is greater than max 20
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/var_array.rb:29:in `read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:18:in `block (2 levels) in read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:17:in `each'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:17:in `block in read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:16:in `tap'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:16:in `read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/union.rb:40:in `read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/union.rb:40:in `read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/var_array.rb:32:in `block in read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/var_array.rb:32:in `times'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/var_array.rb:32:in `each'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/var_array.rb:32:in `map'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/var_array.rb:32:in `read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:18:in `block (2 levels) in read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:17:in `each'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:17:in `block in read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:16:in `tap'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/struct.rb:16:in `read'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/xdr-0.0.2/lib/xdr/concerns/converts_to_xdr.rb:55:in `from_xdr'
	/Users/andrewrogers/Code/stellar/horizon/app/models/hayashi/transaction.rb:32:in `meta'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/memoist-0.11.0/lib/memoist.rb:130:in `meta'
	/Users/andrewrogers/Code/stellar/horizon/app/models/hayashi/transaction.rb:62:in `participants'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/memoist-0.11.0/lib/memoist.rb:130:in `participants'
	/Users/andrewrogers/Code/stellar/horizon/app/models/hayashi/transaction.rb:75:in `participant_addresses'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/memoist-0.11.0/lib/memoist.rb:130:in `participant_addresses'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/history/ledger_importer_job.rb:51:in `block (3 levels) in perform'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/history/ledger_importer_job.rb:34:in `each'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/history/ledger_importer_job.rb:34:in `block (2 levels) in perform'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/history/ledger_importer_job.rb:19:in `block in perform'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/application_job.rb:12:in `block in with_db'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/application_job.rb:12:in `with_db'
	/Users/andrewrogers/Code/stellar/horizon/app/jobs/history/ledger_importer_job.rb:16:in `perform'
	/Users/andrewrogers/Code/stellar/horizon/lib/instrumentation.rb:62:in `block (2 levels) in create_instrumented_method'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/metriks-0.9.9.7/lib/metriks/timer.rb:51:in `call'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/metriks-0.9.9.7/lib/metriks/timer.rb:51:in `time'
	/Users/andrewrogers/Code/stellar/horizon/lib/instrumentation.rb:61:in `block in create_instrumented_method'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/Users/andrewrogers/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
Celluloid::PoolManager: async call `perform` aborted!

**Comment by nullstyle** [comment]
This is almost undoubtedly due to XDR mismatches.  testnet hasn't been updated for the new XDR defs

**Comment by nullstyle** [comment]
Fixed
