### ISSUE TITLE
Rename `sending_*` attributes to `source_*`

### ISSUE THREAD

**Issue by nullstyle** [stellar/horizon#4]
With the move to "multi-operation" transactions, the notion of someone sending a transaction is pretty murky.  Really, what used to be "the sending account" is probably most accurately described as "The account that pays for the transaction via sequence number and fees", which I think we should just refer to as the "submitting" account.

**Comment by malandrina** [comment]
Looks like this is done? https://github.com/stellar/horizon/commit/0492def0423fa11fd8f632e573079270405100c1

**Comment by nullstyle** [comment]
Well, I'm goign to be adding back a lot of that PendingTransaction stuff soon.  We pulled it out of this initial launch because of time constraints.  

Regardless, though, I actually am going to synchronize the term used with stellar-core:  "source account"

I'm going to leave this open, as a reminder to myself cleanup when I add that code back.

Thanks!

**Comment by malandrina** [comment]
Got it. Sounds good!
